### ISSUE TITLE
ChannelInfo.ActiveClip is always null

### ISSUE THREAD

**Issue by jcalado** [dust63/StartDust.CasparCG.net#1]
**CasparCG Version** (to get version send command VERSION)
Version: 2.3.0 7829b13b Dev

**Describe the bug**
ActiveClip property is always null

**To Reproduce**
1. LOADBG 1-1 AMB
2. PLAY 1-1
3. casparcgServer.channels.FirstOrDefault().ActiveClip is null

**Expected behavior**
ActiveClip is populated with information from the playing clip

**Comment by dust63** [comment]
I will try to reproduce the problem

**Comment by dust63** [comment]
Seems that AMCP Protocol not sent the active clip on info command. Can you confirm that ?
If yes, I had to remove the property Active Clip.

**Comment by jcalado** [comment]
Yup, no active clip.
Thanks for checking it out.
