### ISSUE TITLE
OSC Event hub broken - missing method

### ISSUE THREAD

**Issue by jcalado** [dust63/StartDust.CasparCG.net#2]
**CasparCG Version** (to get version send command VERSION)
Version: 2.3.0 6497e78f5 RC

**Describe the bug**

Using latest alpha versions of nuget packages:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Void StarDust.CasparCG.net.OSC.IOscListener.add_ListenerStarted(System.EventHandler)'.
   at StarDust.CasparCG.net.OSC.EventHub.CasparCGOscEventsHub..ctor(IOscListener casparCgOscListener)
```

**To Reproduce**
1. Use the provided OSC event hub code on the repo

**Comment by jcalado** [comment]
https://github.com/dust63/StartDust.CasparCG.net/blob/707aae12cb934dd1b7306b5e2b71f258842c4939/src/StarDust.CasparCG.net.OSC.EventHub/EventHub.cs#L95

This check seems to be the offending line, since commenting it yields a working (?) status.

**Comment by dust63** [comment]
Hi, can you retry with last version 2020.7.17.1 of OSC Event Hub ? I had a mistake with the OSC nuget package. I just upload the 2020.7.18.1 version.

**Comment by jcalado** [comment]
That fixed it :) Thank you!
