### ISSUE TITLE
disable formatting of xml optioin

### ISSUE THREAD

**Issue by Erie1** [dust63/StartDust.CasparCG.net#6]
https://github.com/dust63/StartDust.CasparCG.net/blob/96a20bdda6bac923d451c9ceeac342316d0ea2ed/src/StarDust.CasparCG.net.Models/Datas/CasparCGDataCollection.cs#L57-L60

While using the dataCollection to send templateData to my server I noticed that the XML is formatted using whitespace which is not properly parsed by caspar when using DOMparser in js. It would be great if it was somehow possible to set "SaveOptions.DisableFormatting" in the "XElement.ToString()" at the end of the "ToXml()" function.

**Comment by dust63** [comment]
New nuget packages are released ;)

**Comment by Erie1** [comment]
thanks for the enhancement, however I can't update my nuget package because the OSCEventHub depends on a newer version of OSC than exists yet(2021.11.17.1 vs 2020.7.18.1)

**Comment by dust63** [comment]
I just republish osc libs

**Comment by Erie1** [comment]
As I was moving over to the new nuget packages I noticed that the "replace()" functions at the end of "ToXml" were removed, introducing some new bugs when using this function, could these lines be added back? or was there a reason they were deleted?

Edit: after some additional testing, only ".Replace("\"", "\\\"");" is required to fix the problem; saveOptions removes the tabs and endlines, but doesn's prefix quotes with a backslash

**Comment by dust63** [comment]
Sorry I will fixe that soon

**Comment by dust63** [comment]
Fix available on 2022.1.6.1
